#!/usr/bin/perl

# ----------------------------------------------------------------------
# Usage examples
# ==============
#
# cd /scratch/ursl/store/user/ursl/bmm4/cmsRun/v06/bmmMuOnia2011A
# $BMMBASE/perl/collectCrabRootfiles -n bmm-rereco-Run2011A ../MuOnia/crab_BMM4_Run2011A/170606_062613/*
# $BMMBASE/perl/collectCrabRootfiles -n bmm-rereco-Run2011A ../MuOnia/crab_BMM4_Run2011A/170606_062613*
# $BMMBASE/perl/collectCrabRootfiles -d  ../legacy/Run2016H-07Aug17-v1/Charmonium/crab_BMM4_legacy-Run2016H-v1/171201_104724/000*

#  -c: enable counter that changes the name of rootfiles (else the files are simply moved)
#
# ----------------------------------------------------------------------
# Send all questions, wishes and complaints to the
#
# Author    Urs Langenegger <urslangenegger@gmail.com>
# ----------------------------------------------------------------------


use lib "$ENV{BMMBASE}/perl/modules/Tie-IxHash-1.23/lib";
use Tie::IxHash;

use Cwd;

use Getopt::Std;
getopts('cdn:o:x:');

my $dir = cwd();

my @Xdir;
foreach $elem (@ARGV) {
    print "adding $elem\n";
    push(@Xdir, $elem);
}

my $name = "crab";
if ($opt_n) {
    $name = $opt_n;
}

my $BMMBASE = $ENV{BMMBASE};
my $USER = $ENV{USER};

my $cnt = 0;
if ($opt_o) {
    $cnt = $opt_o;
}

my $xdir = ".";
foreach $xdir (@Xdir) {
    print "dir  = $dir\n";
    print "xdir = $xdir\n";
    print "name = $name\n";
    print "offset = $cnt\n";

    chdir("$xdir");
    print "cd to ", cwd(), "\n";
    @rootfiles = `find . -name "*.root" -print`;
    chdir("$dir");
    print "cd to ", cwd(), "\n";

    unlink("$xdir/collectcrab.$name");
    open(OUT, ">$xdir/collectcrab.$name") || die "cannot open $xdir/collectcrab.$name\n";

    foreach $file (@rootfiles) {
	chop($file);
	if ($file =~ /failed/) {next;}
	$file =~ s%\.\/%%g;
	$numeral = sprintf("%04i", $cnt);
	if ($opt_c) {
	    $newrootfilename = "$name-$numeral.root";
	} else {
	    $newrootfilename = "$file";
	}
	print "mv $xdir/$file $newrootfilename\n";
	print OUT "$xdir/$file -> $newrootfilename\n";
	if (-e "$dir/$newrootfilename") {
	    print "$dir/$newrootfilename already exists, skip this one\n";
	}
	if (!$opt_d) {
	    if (-e "$dir/$newrootfilename") {
		print "$dir/$newrootfilename already exists, skip this one\n";
	    } else {
		system("mv $xdir/$file $dir/$newrootfilename");
	    }
	}
	$cnt++;
    }
}

close OUT;
