#!/usr/bin/perl

# ----------------------------------------------------------------------
# Usage examples
# ==============
#
# /scratch/ursl/store/user/ursl/bmm4/cmsRun/v06/bmmMuOnia2011A
# $BMMBASE/perl/collectCrabRootfiles -x MuOnia/crab_BMM4_Run2011A/170606_062613/ -n bmm-rereco-Run2011A
# $BMMBASE/perl/collectCrabRootfiles -x MuOnia/crab_BMM4_Run2011A/170606_062613 -n bmm-rereco-Run2011A
# ----------------------------------------------------------------------
# Send all questions, wishes and complaints to the
#
# Author    Urs Langenegger <urslangenegger@gmail.com>
# ----------------------------------------------------------------------


use lib "$ENV{BMMBASE}/perl/modules/Tie-IxHash-1.23/lib";
use Tie::IxHash;

use Cwd;

use Getopt::Std;
getopts('dn:o:x:');

my $dir = cwd();

my $xdir = ".";
if ($opt_x) {
    $xdir = $opt_x;
}

my $name = "crab";
if ($opt_n) {
    $name = $opt_n;
}

my $BMMBASE = $ENV{BMMBASE};
my $USER = $ENV{USER};

my $cnt = 0;
if ($opt_o) {
    $cnt = $opt_o;
}

print "dir  = $dir\n";
print "xdir = $xdir\n";
print "name = $name\n";
print "offset = $cnt\n";

chdir("$xdir");
print "cd to ", cwd(), "\n";
@rootfiles = `find . -name "*.root" -print`;
chdir("$dir");
print "cd to ", cwd(), "\n";

#@rootfiles;

unlink("$xdir/collectcrab.$name");
open(OUT, ">$xdir/collectcrab.$name") || die "cannot open $xdir/collectcrab.$name\n";

foreach $file (@rootfiles) {
    chop($file);
    if ($file =~ /failed/) {next;}
    $file =~ s%\.\/%%g;
    $numeral = sprintf("%04i", $cnt);
    $newrootfilename = "$name-$numeral.root";
    print "mv $xdir/$file $newrootfilename\n";
    print OUT "$xdir/$file -> $newrootfilename\n";
    if (!$opt_d) {
	system("mv $xdir/$file $dir/$newrootfilename");
    }
    $cnt++;
}

close OUT;
