#!/usr/bin/env perl

use Getopt::Std;
getopts('d:v:');

my $dir = "..";
if ($opt_d) {
    $dir = $opt_d;
}
if ($opt_v eq "v10") {
    system("ln -s $dir/plotResults.2016BFv10.files");
    system("ln -s $dir/plotResults.2016GHv10.files");
} else {
    system("ln -s $dir/plotResults.2016BF.files");
    system("ln -s $dir/plotResults.2016GH.files");
}
system("ln -s $dir/plotResults.2012.files");
system("ln -s $dir/plotResults.2011.files");

system("/bin/cp $dir/cuts/baseCuts.2016.cuts .");
system("/bin/cp $dir/cuts/baseCuts.2011.cuts .");
system("/bin/cp $dir/cuts/baseCuts.2012.cuts .");

system("mkdir -p overlays/2016");
system("mkdir -p overlays/2012");
system("mkdir -p overlays/2011");
system("mkdir -p sbso");
system("mkdir -p adfpy");
system("mkdir -p sbsctrl");
