#!/usr/bin/env perl

#
# $BMMBASE/perl/emptyfiles -r .py /path/to/somewhere/*.py 
#
# ----------------------------------------------------------------------
# Send all questions, wishes and complaints to the 
#
# Author    Urs Langenegger <urs.langenegger@gmail.com>
# ----------------------------------------------------------------------

use File::Basename;

use Getopt::Std;
getopts('dr:');

foreach $file (@ARGV) {
    ($fname = basename($file)) =~ s/$opt_r//g;
    print "touch $fname\n";
    if (!$opt_d) {
	system("touch $fname");
    }
}
