#!/usr/bin/env perl

# ----------------------------------------------------------------------
#
# Usage: cd $BMMBASE/..; $BMMBASE/perl/mkTarFile 150701.tar.gz
# -----  cd $BMMBASE/../..; src/$BMMBASE/perl/mkTarFile -c 150701nc.tar.gz
#
#          -c  complete (for jobs without compilation)
#          -s  slim format (not supported at the moment)
# ----------------------------------------------------------------------

# -s slim
# -c complete (to be invoked from CMSSW_X_Y_Z, allows to be used w/o compilation)

use Getopt::Std;
getopts('ci:s');

if ($ARGV[0]) {
    $name = $ARGV[0];
} else {
    die "need a name for the tarfile\n";
}

$include  = "Bmm/CmsswAnalysis Bmm/RootAnalysis ";

if ($opt_c) {
    ($include = $include) =~ s%Bmm%src/Bmm%g;
    $include .= " lib config python"; 
}    

if ($opt_i) {
    $include .= " $opt_i";
}

$exclude .= " --exclude .git";
$exclude .= " --exclude obj/\\*.o";
$exclude .= " --exclude Bmm/CmsswAnalysis/test";
$exclude .= " --exclude \\*.root";
$exclude .= " --exclude \\*.pdf";
$exclude .= " --exclude \\*.ps";
$exclude .= " --exclude \\*.eps";
$exclude .= " --exclude \\*~";
$exclude .= " --exclude \\*Dict\\*";

system("tar zcvf $name $include $exclude"); 
print("tar zcvf $name $include $exclude  --wildcards\n"); 
