#!/usr/bin/env perl

# script for patching py files created by cmsDriver.py


@insert = ("# -- Reduced verbosity\n",
	   "process.load(\"FWCore.MessageLogger.MessageLogger_cfi\")\n",
	   "process.MessageLogger.cerr.threshold = 'INFO'\n",
	   "process.MessageLogger.cerr.FwkReport.reportEvery = 1000\n",
           "# Random number\n",
	   "process.RandomNumberGeneratorService = cms.Service(\"RandomNumberGeneratorService\",\n",
	   "                                                   generator = cms.PSet(initialSeed = cms.untracked.uint32(40000)),\n",
	   "                                                   VtxSmeared = cms.PSet(initialSeed = cms.untracked.uint32(40000)),\n",
	   "                                                   g4SimHits =  cms.PSet(initialSeed = cms.untracked.uint32(40000))\n",
           "                                                   )\n"
    );



foreach $file (@ARGV) {
    open(FH, "+< $file")                 or die "Opening: $!";
    @ARRAY = <FH>;
    # change ARRAY here
    for ($i; $i < $#ARRAY; $i++) {
	if ($ARRAY[$i] =~ /EmptySource/) {
	    splice @ARRAY, $i-1, 0, @insert;
	    last; 
	}
    }

    seek(FH,0,0)                        or die "Seeking: $!";
    print FH @ARRAY                     or die "Printing: $!";
    truncate(FH,tell(FH))               or die "Truncating: $!";
    close(FH)                           or die "Closing: $!";
}


