#!/usr/bin/env perl

# ----------------------------------------------------------------------
#
# Usage: seFiles -x /store/user/ursl/bmm4/small/170828 -p small201
# -----
#
#        dumps small, reduced, and LaTeX files of analysis to SE
#        assumes that /scratch/ursl/store is mounted
#
#        $BMMBASE/perl/seFiles -x /store/user/ursl/bmm4/small/170828 -p 'small20*.root'
#        $BMMBASE/perl/seFiles -x /store/user/ursl/bmm4/small/170828 -p 'plotResults*.tex'
#        $BMMBASE/perl/seFiles -x /store/user/ursl/bmm4/reduced/170828 -p 'bmm-*.root'
#
# ----------------------------------------------------------------------
# Send all questions, wishes and complaints to the
#
# Author    Urs Langenegger <urslangenegger@gmail.com>
# ----------------------------------------------------------------------

use Getopt::Std;
getopts('p:x:');


my $fileglob  = $opt_p;
my $srmprefix = 'srm://t3se01.psi.ch:8443/srm/managerv2?SFN=/pnfs/psi.ch/cms/trivcat';
my $xroot     = 'root://t3se01.psi.ch:1094/pnfs/psi.ch/cms/trivcat';
my $scratch   = '/scratch/ursl';

@files = <" $opt_p ">;
my @files = `/bin/ls -1 $opt_p`;


if (!-d "$scratch/$opt_x") {
    print "create $srmprefix/$opt_x\n";
    system("srmmkdir $srmprefix/$opt_x");
} else {
    print "OK: $srmprefix/$opt_x\n";
}

foreach $file (@files) {
    chop($file);
    print "$file\n";
    system("xrdcp $file $xroot/$opt_x/$file");
}
