#!/usr/bin/env perl

# ----------------------------------------------------------------------
#
# Usage: srmHadd -x URI -p pattern [-d] [-a "-count=900"] -o output.root
# -----
#
# Examples: srmHadd \
#           -x srm://t3se01.psi.ch:8443/srm/managerv2\?SFN=/pnfs/psi.ch/cms/trivcat/store/user/ursl/bmm4/runBmm/v01//Summer15_private \
#           -p bmm-mc-Summer15_private-recoil0-v01 \
#           -o /scratch/ursl/bmm4/v01/bmm-mc-Summer15_private-recoil0-v01.root
#
# ----------------------------------------------------------------------

my $root    = "root://t3dcachedb.psi.ch:1094/pnfs/psi.ch/cms/trivcat";
my $dcap    = "dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat";
my $psi     = "srm://t3se01.psi.ch:8443/srm/managerv2\?SFN=/pnfs/psi.ch/cms/trivcat";


# -- Get arguments
use Getopt::Std;
getopts('a:do:p:x:');

my $BMMBASE = $ENV{'BMMBASE'};

# -- arguments for srmls
if ($opt_a) {
    ($arg = $opt_a) =~ s/\"//g;
    print "--> srmHadd $arg $opt_x\n";
}

my $output = "merged.root";
if ($opt_o) {$output = $opt_o;}

my $pattern = "\\.root\$";
if ($opt_p) {$pattern = $opt_p;}

@merges = `$BMMBASE/perl/srmLs -x $opt_x -c -p $pattern`;

# -- prepare list
foreach $f (@merges) {
    chop($f);
    $f =~ s/^\ *//g;
    #    print "dbx: $f\n";
    if ($f =~ /$pattern/) {
	print "pattern found: $f\n";
	push(@urootfiles, $f);
    }
}
@rootfiles = sort(@urootfiles);

# -- now do it
if ($opt_d) {
    print "hadd $output \n";
    foreach $f (@rootfiles) {print "  $f\n";}
    exit(0);
} else {
    if ($#rootfiles > 0) {
	print "hadd $output @rootfiles\n";
	if (-e "$output") {unlink("$output"); }
	system("hadd $output @rootfiles");
    } else {
	($oneFile = $rootfiles[0]) =~ s%$dcap%$psi%g;
	if (-e "$output") {unlink("$output"); }
	print "lcg-cp -b -D srmv2 $oneFile $output \n";
	system("lcg-cp -b -D srmv2 $oneFile $output");
    }
}
