#!/usr/bin/env perl

# ----------------------------------------------------------------------
#
# Usage: xFiles -x /store/user/ursl/bmm4/small/170828 -p small201
# -----
#        assumes that /scratch/ursl/store is mounted
#        get files matching patter $opt_p to pwd.
#
#        $BMMBASE/perl/xFiles -x /store/user/ursl/bmm4/small/170828 -p 'small20*.root'
#
# ----------------------------------------------------------------------
# Send all questions, wishes and complaints to the
#
# Author    Urs Langenegger <urslangenegger@gmail.com>
# ----------------------------------------------------------------------

use Getopt::Std;
getopts('p:x:');


my $fileglob  = $opt_p;
my $srmprefix = 'srm://t3se01.psi.ch:8443/srm/managerv2?SFN=/pnfs/psi.ch/cms/trivcat';
my $xroot     = 'root://t3se01.psi.ch:1094/pnfs/psi.ch/cms/trivcat';
my $scratch   = '/scratch/ursl';

my $xdir = $scratch . $opt_x;

my @files = `/bin/ls -1 $xdir |/bin/grep $opt_p`;

my $command = "";
foreach $file (@files) {
    chop($file);
    $command = "xrdcp $xroot/$opt_x/$file $file";
    print "$command \n";
#    system("$command");
#    sleep(2);
}
